### ISSUE TITLE
Disabling Frame Timeline

### ISSUE THREAD

**Issue by vushu** [PDFTron/webviewer-video-sample#5]
Hi how do I disable the frames timeline?

**Comment by willywwang** [comment]
Hi vushu, 

We added the ability to toggle the frames in 3.9 of Webviewer-video. When calling `renderControlsToDOM` all you need to do is pass in the object as such:

        ```
const videoSettings = {
    showFrames: false,
};

renderControlsToDOM(instance, customContainer, videoSettings);
```
